site_name: Convertlab 文档中心

site_url: http://api-docs.convertlab.com/

repo_url: https://github.com/xsio/open_api_docs

theme_dir: themes/mkdocs

theme_center_lead: false

include_search: true

include_next_prev: false

copyright: Copyright &copy; 2017, Convertlab

pages:
#- [index.md, '文档首页', '文档首页']
- [index.md, 'OpenAPI V1', '创建集成应用']
- [api/accesstoken.md, 'OpenAPI V1', '获取身份权限']
- [api/customer.md, 'OpenAPI V1', '客户信息']
- [api/customerevent.md, 'OpenAPI V1', '客户事件']
- [api/tag.md, 'OpenAPI V1', '客户标签']
- [api/deal.md, 'OpenAPI V1', '客户订单']
- [track/index.md, '网页埋点', '设置埋点']
- [track/customevent.md, '网页埋点', '客户自定义事件']
- [track/sourcetracking.md, '网页埋点', '来源跟踪']
- [test/index.md, 'TRY IT', 'TRY IT']
